### ISSUE TITLE
Unable to build on OSX 10.14 Mojave

### ISSUE THREAD

**Issue by johnptoohey** [veres-one/did-client-veres-one#3]
Had this working on previous OSX but after upgrading to 10.14 and latest node, Trying npm install did-client I get : 
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/11.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/johntoohey/node_modules/sodium-native
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN saveError ENOENT: no such file or directory, open '/Users/johntoohey/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/johntoohey/package.json'
npm WARN johntoohey No description
npm WARN johntoohey No repository field.
npm WARN johntoohey No README data
npm WARN johntoohey No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.2.2 (node_modules/sodium-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sodium-native@2.2.2 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by msporny** [comment]
Hmm, looks like a bug in the sodium-native dependency that presumes a particular directory setup that doesn't work on Mac OS X... unfortunately out of our control, but we'll take a look at it to see if there is a workaround on OS X.

**Comment by johnptoohey** [comment]
I do have a /Users/johntoohey/node_modules/libsodium directory, and a package-lock.json file in my home directory.
